
package extract.autoVoiceExtract;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Epoint005WebServiceService", targetNamespace = "http://service_005.epoint.com/", wsdlLocation = "http://218.4.136.118:81/05557WebService/services/Epoint005WebService?wsdl")
public class Epoint005WebServiceService
    extends Service
{

    private final static URL EPOINT005WEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EPOINT005WEBSERVICESERVICE_EXCEPTION;
    private final static QName EPOINT005WEBSERVICESERVICE_QNAME = new QName("http://service_005.epoint.com/", "Epoint005WebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://218.4.136.118:81/05557WebService/services/Epoint005WebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EPOINT005WEBSERVICESERVICE_WSDL_LOCATION = url;
        EPOINT005WEBSERVICESERVICE_EXCEPTION = e;
    }

    public Epoint005WebServiceService() {
        super(__getWsdlLocation(), EPOINT005WEBSERVICESERVICE_QNAME);
    }

    public Epoint005WebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EPOINT005WEBSERVICESERVICE_QNAME, features);
    }

    public Epoint005WebServiceService(URL wsdlLocation) {
        super(wsdlLocation, EPOINT005WEBSERVICESERVICE_QNAME);
    }

    public Epoint005WebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EPOINT005WEBSERVICESERVICE_QNAME, features);
    }

    public Epoint005WebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Epoint005WebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Epoint005WebService
     */
    @WebEndpoint(name = "Epoint005WebServicePort")
    public Epoint005WebService getEpoint005WebServicePort() {
        return super.getPort(new QName("http://service_005.epoint.com/", "Epoint005WebServicePort"), Epoint005WebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Epoint005WebService
     */
    @WebEndpoint(name = "Epoint005WebServicePort")
    public Epoint005WebService getEpoint005WebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service_005.epoint.com/", "Epoint005WebServicePort"), Epoint005WebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EPOINT005WEBSERVICESERVICE_EXCEPTION!= null) {
            throw EPOINT005WEBSERVICESERVICE_EXCEPTION;
        }
        return EPOINT005WEBSERVICESERVICE_WSDL_LOCATION;
    }

}
