
package extract.autoVoiceExtract;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Epoint005WebService", targetNamespace = "http://service_005.epoint.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Epoint005WebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "expertResult", targetNamespace = "http://service_005.epoint.com/", className = "extract.autoVoiceExtract.ExpertResult")
    @ResponseWrapper(localName = "expertResultResponse", targetNamespace = "http://service_005.epoint.com/", className = "extract.autoVoiceExtract.ExpertResultResponse")
    public String expertResult(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "putObject", targetNamespace = "http://service_005.epoint.com/", className = "extract.autoVoiceExtract.PutObject")
    @ResponseWrapper(localName = "putObjectResponse", targetNamespace = "http://service_005.epoint.com/", className = "extract.autoVoiceExtract.PutObjectResponse")
    public String putObject(
        @WebParam(name = "arg0", targetNamespace = "")
        ProjectYytz arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
