
package test.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DemoService", targetNamespace = "http://webservice.test/", wsdlLocation = "http://192.168.1.140:456/helloWord?wsdl")
public class DemoService
    extends Service
{

    private final static URL DEMOSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEMOSERVICE_EXCEPTION;
    private final static QName DEMOSERVICE_QNAME = new QName("http://webservice.test/", "DemoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.140:456/helloWord?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEMOSERVICE_WSDL_LOCATION = url;
        DEMOSERVICE_EXCEPTION = e;
    }

    public DemoService() {
        super(__getWsdlLocation(), DEMOSERVICE_QNAME);
    }

    public DemoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEMOSERVICE_QNAME, features);
    }

    public DemoService(URL wsdlLocation) {
        super(wsdlLocation, DEMOSERVICE_QNAME);
    }

    public DemoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEMOSERVICE_QNAME, features);
    }

    public DemoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Demo
     */
    @WebEndpoint(name = "DemoPort")
    public Demo getDemoPort() {
        return super.getPort(new QName("http://webservice.test/", "DemoPort"), Demo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Demo
     */
    @WebEndpoint(name = "DemoPort")
    public Demo getDemoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.test/", "DemoPort"), Demo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEMOSERVICE_EXCEPTION!= null) {
            throw DEMOSERVICE_EXCEPTION;
        }
        return DEMOSERVICE_WSDL_LOCATION;
    }

}
