
package test.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Demo", targetNamespace = "http://webservice.test/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Demo {


    /**
     * 
     * @param arg0
     * @return
     *     returns test.webservice.User
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.test/Demo/getUserRequest", output = "http://webservice.test/Demo/getUserResponse")
    public User getUser(
        @WebParam(name = "arg0", partName = "arg0")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.test/Demo/callBackRequest", output = "http://webservice.test/Demo/callBackResponse")
    public String callBack(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.test/Demo/sayHelloRequest", output = "http://webservice.test/Demo/sayHelloResponse")
    public String sayHello();

}
